export enum EnumPaginas {
    DASHBOARD = 'DASHBOARD',
    OPORTUNIDADES_GENERAL = 'OPORTUNIDADES GENERAL',
    OPORTUNIDADES_POR_AGENTE = 'OPORTUNIDADES POR AGENTE',
    CLIENTES_TOP_20 = 'CLIENTES TOP 20',
    PROSPECTOS = 'PROSPECTOS',
    CONTACTOS = 'CONTACTOS',

}