export enum EnumMenus {
    DASHBOARD = 'DASHBOARD',
    EN_PROCESO = 'EN PROCESO',
    TERMINADAS = 'TERMINADAS',
    ADMINISTRACION  = 'ADMINISTRACIÓN',
    USUARIOS = 'USUARIOS',
    HERRAMIENTAS = 'HERRAMIENTAS',
    CONFIGURACION = 'CONFIGURACIÓN',
}